# SERVER
server.port=8081

# DATABASE (LOCAL)
spring.datasource.url=jdbc:mysql://localhost:3306/quizapplicationsss
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# LIQUIBASE
spring.liquibase.change-log=config/liquibase/master.xml
spring.liquibase.enabled=true
logging.level.liquibase=DEBUG

# RAZORPAY TEST KEYS
razorpay.key.id=rzp_test_SOMFrqPuk1vsGU
razorpay.key.secret=dRuRfrs80oGR9QQ1WFAWrXZK

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sakshikore8070@gmail.com
spring.mail.password=qobg rczi dasr lsgw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ADMIN EMAIL
admin.email=sakshikore8070@gmail.com

# DEEPSEEK API
deepseek.api.key=sk-599d1306065b46c69d333ea71f102290
deepseek.enabled=true