# SERVER
server.port=8081

# DATABASE (PRODUCTION SERVER)
spring.datasource.url=jdbc:mysql://prod-db-server:3306/quizapplicationsss
spring.datasource.username=prod_user
spring.datasource.password=StrongPassword123

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# LIQUIBASE
spring.liquibase.change-log=config/liquibase/master.xml
spring.liquibase.enabled=true

# RAZORPAY LIVE KEYS
razorpay.key.id=rzp_live_xxxxxxxxx
razorpay.key.secret=live_secret_key

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=production@company.com
spring.mail.password=securepassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ADMIN EMAIL
admin.email=admin@company.com

# DEEPSEEK API
deepseek.api.key=prod_deepseek_key
deepseek.enabled=true